package ru.yandex.javacourse.schedule.manager;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import ru.yandex.javacourse.schedule.tasks.Epic;
import ru.yandex.javacourse.schedule.tasks.Subtask;
import ru.yandex.javacourse.schedule.tasks.Task;
import ru.yandex.javacourse.schedule.tasks.TaskStatus;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

public class InMemoryTaskManagerTest {

    TaskManager manager;

    @BeforeEach
    public void initManager(){
        manager = Managers.getDefault();
    }

    @Test
    public void testAddTask() {
        Task task = new Task("Test 1", "Testing task 1", TaskStatus.NEW);
        manager.addNewTask(task);
        assertEquals(1, manager.getTasks().size(), "task should be added");
        Task addedTask = manager.getTasks().get(0);
        assertEquals(task, addedTask, "added task id should be set");
        Task byIdTask = manager.getTask(task.getId());
        assertEquals(task, byIdTask, "added task id should be found");
    }

    @Test
    public void testAddTaskWithId(){
        Task task = new Task("Test 1", "Testing task 1", TaskStatus.NEW);
        manager.addNewTask(task);
        assertEquals(1, manager.getTasks().size(), "task should be added");
        Task addedTask = manager.getTasks().get(0);
        assertEquals(task, addedTask, "predefined task id should be set");
    }

    @Test
    public void testAddTaskWithoutId(){
        Task task0 = new Task("Test 1", "Testing task 1", TaskStatus.NEW);
        Task task1 = new Task( "Test 2", "Testing task 2", TaskStatus.NEW);
        manager.addNewTask(task0);
        manager.addNewTask(task1);
        assertEquals(2, manager.getTasks().size(), "lost a task with predefined id");
        assertEquals(1, task0.getId(), "autogenerated id should be 1");
    }

    @Test
    public void checkTaskNotChangedAfterAddTask() {
        String name = "Test 1";
        String description = "Testing task 1";
        TaskStatus status = TaskStatus.NEW;
        Task task1before = new Task( name, description, status);
        manager.addNewTask(task1before);
        Task task1after = manager.getTask(task1before.getId());
        assertEquals(description, task1after.getDescription());
        assertEquals(status, task1after.getStatus());
        assertEquals(name, task1after.getName());
    }


    @Test
    public void testGetEpicSubtasks() {
        Epic epic = new Epic(1, "Epic 1", "Test epic 1");
        Subtask subtask1 = new Subtask(2, "Subtask 1", "Test subtask 1", TaskStatus.NEW, epic.getId());
        Subtask subtask2 = new Subtask(3, "Subtask 2", "Test subtask 2", TaskStatus.NEW, epic.getId());


        manager.addNewEpic(epic);

        final Integer subtaskId1 = manager.addNewSubtask(subtask1);
        final Integer subtaskId2 = manager.addNewSubtask(subtask2);

        epic.addSubtaskId(subtaskId1);
        epic.addSubtaskId(subtaskId2);

        List<Subtask> subtasks = manager.getEpicSubtasks(1);

        assertNotNull(subtasks);
        assertEquals(2, subtasks.size());
        assertTrue(subtasks.contains(subtask1));
        assertTrue(subtasks.contains(subtask2));
    }


    @Test
    public void testDeleteSubtask() {
        Epic epic = new Epic(1, "Epic 1", "Test epic 1");
        Subtask subtask1 = new Subtask(2, "Subtask 1", "Test subtask 1", TaskStatus.NEW, epic.getId());
        Subtask subtask2 = new Subtask(3, "Subtask 2", "Test subtask 2", TaskStatus.NEW, epic.getId());

        manager.addNewEpic(epic);
        manager.addNewSubtask(subtask1);
        manager.addNewSubtask(subtask2);

        epic.addSubtaskId(subtask1.getId());
        epic.addSubtaskId(subtask2.getId());

        assertEquals(2, epic.getSubtaskIds().size(), "Epic should have 2 subtasks initially");

        manager.deleteSubtask(subtask1.getId());

        assertNull(manager.getSubtask(subtask1.getId()), "Subtask 1 should be null after deletion");
        assertFalse(epic.getSubtaskIds().contains(subtask1.getId()), "Epic should no longer contain Subtask 1");
        assertTrue(epic.getSubtaskIds().contains(subtask2.getId()), "Epic should still contain Subtask 2");
    }


    @Test
    public void testDeleteEpic() {
        Epic epic = new Epic(1,"Epic 1", "Test epic");
        Subtask subtask1 = new Subtask(2,"Subtask 1", "Test subtask 1", TaskStatus.NEW, epic.getId());
        Subtask subtask2 = new Subtask(3,"Subtask 2", "Test subtask 2", TaskStatus.NEW, epic.getId());

        manager.addNewEpic(epic);
        manager.addNewSubtask(subtask1);
        manager.addNewSubtask(subtask2);

        epic.addSubtaskId(subtask1.getId());
        epic.addSubtaskId(subtask2.getId());

        assertNotNull(manager.getEpic(1), "Epic should exist before deletion");
        assertNotNull(manager.getSubtask(2), "Subtask 1 should exist before deletion");
        assertNotNull(manager.getSubtask(3), "Subtask 2 should exist before deletion");

        manager.deleteEpic(1);

        assertNull(manager.getEpic(1), "Epic should be deleted");
        assertNull(manager.getSubtask(2), "Subtask 1 should be deleted");
        assertNull(manager.getSubtask(3), "Subtask 2 should be deleted");
    }


    @Test
    public void testDeleteSubtasks() {
        Epic epic1 = new Epic(1, "Epic 1", "Test epic 1");
        Epic epic2 = new Epic(2, "Epic 2", "Test epic 2");

        Subtask subtask1 = new Subtask(3, "Subtask 1", "Test subtask 1", TaskStatus.NEW, epic1.getId());
        Subtask subtask2 = new Subtask(4, "Subtask 2", "Test subtask 2", TaskStatus.NEW, epic1.getId());
        Subtask subtask3 = new Subtask(5, "Subtask 3", "Test subtask 3", TaskStatus.NEW, epic2.getId());

        manager.addNewEpic(epic1);
        manager.addNewEpic(epic2);
        manager.addNewSubtask(subtask1);
        manager.addNewSubtask(subtask2);
        manager.addNewSubtask(subtask3);

        epic1.addSubtaskId(subtask1.getId());
        epic1.addSubtaskId(subtask2.getId());
        epic2.addSubtaskId(subtask3.getId());

        assertEquals(3, manager.getSubtasks().size(), "Subtasks should be in the manager before deletion");
        assertEquals(2, manager.getEpics().size(), "Epics should be in the manager before deletion");

        manager.deleteSubtasks();

        assertEquals(0, manager.getSubtasks().size(), "Subtasks should be deleted");

        assertTrue(epic1.getSubtaskIds().isEmpty(), "Epic 1 should have no subtasks after deletion");
        assertTrue(epic2.getSubtaskIds().isEmpty(), "Epic 2 should have no subtasks after deletion");
    }
}
