package ru.yandex.javacourse.schedule.manager;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import ru.yandex.javacourse.schedule.tasks.Epic;
import ru.yandex.javacourse.schedule.tasks.Subtask;
import ru.yandex.javacourse.schedule.tasks.Task;
import ru.yandex.javacourse.schedule.tasks.TaskStatus;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;
import static ru.yandex.javacourse.schedule.testdata.TestConstants.*;
import static ru.yandex.javacourse.schedule.testdata.TestDataFactory.*;

public class InMemoryTaskManagerTest {

    TaskManager manager;

    @BeforeEach
    public void initManager(){
        manager = Managers.getDefault();
    }

    @Test
    @DisplayName("Задачи: добавление новой задачи присваивает id и позволяет её получить")
    public void addNewTask_TaskIsAddedAndRetrievable() {
        Task task = newTask(TASK_NAME_1, TASK_DESC_1, TaskStatus.NEW);

        manager.addNewTask(task);

        assertEquals(1, manager.getTasks().size(), "task should be added");
        Task addedTask = manager.getTasks().get(0);
        assertEquals(task, addedTask, "added task id should be set");
        Task byIdTask = manager.getTask(task.getId());
        assertEquals(task, byIdTask, "added task id should be found");
    }

    @Test
    @DisplayName("Задачи: менеджер присваивает id новой задаче при добавлении")
    public void addNewTask_WhenTaskHasNoId_AssignsNewId(){
        Task task = newTask(TASK_NAME_1, TASK_DESC_1, TaskStatus.NEW);

        manager.addNewTask(task);

        assertEquals(1, manager.getTasks().size(), "task should be added");
        Task addedTask = manager.getTasks().get(0);
        assertEquals(task, addedTask, "predefined task id should be set");
    }

    @Test
    @DisplayName("Задачи: менеджер присваивает уникальные автоинкрементные id при добавлении нескольких задач")
    public void addNewTask_AssignsSequentialAutoIncrementIds() {
        Task task0 = newTask(TASK_NAME_1, TASK_DESC_1, TaskStatus.NEW);
        Task task1 = newTask(TASK_NAME_2, TASK_DESC_2, TaskStatus.NEW);

        manager.addNewTask(task0);
        manager.addNewTask(task1);

        assertEquals(2, manager.getTasks().size(), "lost a task with predefined id");
        assertEquals(1, task0.getId(), "autogenerated id should be 1");
    }

    @Test
    @DisplayName("Задачи: добавление задачи не изменяет её поля")
    public void addNewTask_FieldsRemainUnchanged() {
        String name = TASK_NAME_1;
        String description = TASK_DESC_1;
        TaskStatus status = TaskStatus.NEW;
        Task task1before = newTask(name, description, status);

        manager.addNewTask(task1before);
        Task task1after = manager.getTask(task1before.getId());

        assertEquals(description, task1after.getDescription());
        assertEquals(status, task1after.getStatus());
        assertEquals(name, task1after.getName());
    }


    @Test
    @DisplayName("Эпик: получение подзадач возвращает все связанные подзадачи")
    public void getEpicSubtasks_ReturnsAllLinkedSubtasks() {
        Epic epic = newEpicWithId(1, EPIC_NAME_1, EPIC_DESC_1);
        Subtask subtask1 = newSubtaskWithId(2, SUBTASK_NAME_1, SUBTASK_DESC_1, TaskStatus.NEW, epic.getId());
        Subtask subtask2 = newSubtaskWithId(3, SUBTASK_NAME_2, SUBTASK_DESC_2, TaskStatus.NEW, epic.getId());

        manager.addNewEpic(epic);
        final Integer subtaskId1 = manager.addNewSubtask(subtask1);
        final Integer subtaskId2 = manager.addNewSubtask(subtask2);
        epic.addSubtaskId(subtaskId1);
        epic.addSubtaskId(subtaskId2);

        List<Subtask> subtasks = manager.getEpicSubtasks(1);

        assertNotNull(subtasks);
        assertEquals(2, subtasks.size());
        assertTrue(subtasks.contains(subtask1));
        assertTrue(subtasks.contains(subtask2));
    }


    @Test
    @DisplayName("Подзадачи: удаление подзадачи по id удаляет связь из эпика")
    public void deleteSubtask_ById_RemovesFromEpic() {
        Epic epic = newEpicWithId(1, EPIC_NAME_1, EPIC_DESC_1);
        Subtask subtask1 = newSubtaskWithId(2, SUBTASK_NAME_1, SUBTASK_DESC_1, TaskStatus.NEW, epic.getId());
        Subtask subtask2 = newSubtaskWithId(3, SUBTASK_NAME_2, SUBTASK_DESC_2, TaskStatus.NEW, epic.getId());

        manager.addNewEpic(epic);
        manager.addNewSubtask(subtask1);
        manager.addNewSubtask(subtask2);
        epic.addSubtaskId(subtask1.getId());
        epic.addSubtaskId(subtask2.getId());

        assertEquals(2, epic.getSubtaskIds().size(), "Epic should have 2 subtasks initially");

        manager.deleteSubtask(subtask1.getId());

        assertNull(manager.getSubtask(subtask1.getId()), "Subtask 1 should be null after deletion");
        assertFalse(epic.getSubtaskIds().contains(subtask1.getId()), "Epic should no longer contain Subtask 1");
        assertTrue(epic.getSubtaskIds().contains(subtask2.getId()), "Epic should still contain Subtask 2");
    }


    @Test
    @DisplayName("Эпик: при удалении эпика должны удаляться все связанные подзадачи")
    public void deleteEpic_ById_RemovesEpicAndItsSubtasks() {
        Epic epic = newEpicWithId(1, EPIC_NAME_1, EPIC_DESC_1);
        Subtask subtask1 = newSubtaskWithId(2, SUBTASK_NAME_1, SUBTASK_DESC_1, TaskStatus.NEW, epic.getId());
        Subtask subtask2 = newSubtaskWithId(3, SUBTASK_NAME_2, SUBTASK_DESC_2, TaskStatus.NEW, epic.getId());

        manager.addNewEpic(epic);
        manager.addNewSubtask(subtask1);
        manager.addNewSubtask(subtask2);
        epic.addSubtaskId(subtask1.getId());
        epic.addSubtaskId(subtask2.getId());

        assertNotNull(manager.getEpic(1), "Epic should exist before deletion");
        assertNotNull(manager.getSubtask(2), "Subtask 1 should exist before deletion");
        assertNotNull(manager.getSubtask(3), "Subtask 2 should exist before deletion");

        manager.deleteEpic(1);

        assertNull(manager.getEpic(1), "Epic should be deleted");
        assertNull(manager.getSubtask(2), "Subtask 1 should be deleted");
        assertNull(manager.getSubtask(3), "Subtask 2 should be deleted");
    }


    @Test
    @DisplayName("Подзадачи: удаление всех подзадач очищает связи у всех эпиков")
    public void deleteSubtasks_All_ClearsEpicRelations() {
        Epic epic1 = newEpicWithId(1, EPIC_NAME_1, EPIC_DESC_1);
        Epic epic2 = newEpicWithId(2, EPIC_NAME_2, EPIC_DESC_2);

        Subtask subtask1 = newSubtaskWithId(3, SUBTASK_NAME_1, SUBTASK_DESC_1, TaskStatus.NEW, epic1.getId());
        Subtask subtask2 = newSubtaskWithId(4, SUBTASK_NAME_2, SUBTASK_DESC_2, TaskStatus.NEW, epic1.getId());
        Subtask subtask3 = newSubtaskWithId(5, SUBTASK_NAME_3, SUBTASK_DESC_3, TaskStatus.NEW, epic2.getId());

        manager.addNewEpic(epic1);
        manager.addNewEpic(epic2);
        manager.addNewSubtask(subtask1);
        manager.addNewSubtask(subtask2);
        manager.addNewSubtask(subtask3);

        epic1.addSubtaskId(subtask1.getId());
        epic1.addSubtaskId(subtask2.getId());
        epic2.addSubtaskId(subtask3.getId());

        assertEquals(3, manager.getSubtasks().size(), "Subtasks should be in the manager before deletion");
        assertEquals(2, manager.getEpics().size(), "Epics should be in the manager before deletion");

        manager.deleteSubtasks();

        assertEquals(0, manager.getSubtasks().size(), "Subtasks should be deleted");
        assertTrue(epic1.getSubtaskIds().isEmpty(), "Epic 1 should have no subtasks after deletion");
        assertTrue(epic2.getSubtaskIds().isEmpty(), "Epic 2 should have no subtasks after deletion");
    }
}
